export const USERS_PROJECT_GET_LOADING = 'USERS_PROJECT_GET_LOADING';
export const USERS_PROJECT_GET_LOADED = 'USERS_PROJECT_GET_LOADED';

export const PROJECTS_GET_LOADING = 'PROJECTS_GET_LOADING';
export const PROJECTS_GET_LOADED = 'PROJECTS_GET_LOADED';
