export const FILTER_FEATURES_DETAILS = 'FILTER_FEATURES_DETAILS';
export const FEATURES_DETAILS_MODAL_OPEN = 'FEATURES_DETAILS_MODAL_OPEN';
export const FEATURES_DETAILS_MODAL_CLOSE = 'FEATURES_DETAILS_MODAL_CLOSE';
export const FEATURES_DETAILS_SET_ALL_FEATURES = 'FEATURES_DETAILS_SET_ALL_FEATURES';