export const FILTER_FEATURES_DETAILS = 'FILTER_FEATURES_DETAILS';
export const FEATURES_DETAILS_MODAL_OPEN = 'FEATURES_DETAILS_MODAL_OPEN';
export const FEATURES_DETAILS_MODAL_CLOSE = 'FEATURES_DETAILS_MODAL_CLOSE';
export const FEATURES_DETAILS_GET_ALL_START_LOADING = 'FEATURES_DETAILS_GET_ALL_START_LOADING';
export const FEATURES_DETAILS_GET_ALL_SUCCESS = 'FEATURES_DETAILS_GET_ALL_SUCCESS';
export const FEATURES_DETAILS_GET_ALL_ERROR = 'FEATURES_DETAILS_GET_ALL_ERROR';