export const PROJECTS_GET_ALL_START_LOADING = 'PROJECTS_GET_ALL_START_LOADING';
export const PROJECTS_GET_ALL_SUCCESS = 'PROJECTS_GET_ALL_SUCCESS';
export const PROJECTS_GET_ALL_ERROR = 'PROJECTS_GET_ALL_ERROR';