export const PROJECTS_GET_ALL_START_LOADING = 'PROJECTS_GET_ALL_START_LOADING';
export const PROJECTS_GET_ALL_SUCCESS = 'PROJECTS_GET_ALL_SUCCESS';
export const PROJECTS_GET_ALL_ERROR = 'PROJECTS_GET_ALL_ERROR';
export const FILTER_PROJECTS_DETAILS = 'FILTER_PROJECTS_DETAILS';
export const FILTER_PROJECTS_BY_TECH_DETAILS = 'FILTER_PROJECTS_BY_TECH_DETAILS';
export const PAGINATION_ACTIVE_PAGE = 'PAGINATION_ACTIVE_PAGE';