export const PROJECT_VIEW_START_LOADING = 'PROJECT_VIEW_START_LOADING';
export const PROJECT_VIEW_END_LOADING = 'PROJECT_VIEW_END_LOADING';
export const PROJECT_VIEW_ERROR_LOADING = 'PROJECT_VIEW_ERROR_LOADING';

export const UPDATE_PROJECT_RATING = 'UPDATE_PROJECT_RATING';
export const SET_RATE_INFO_FAILURE = 'SET_RATE_INFO_FAILURE';
export const GET_RATE_ALL_FAILURE = 'GET_RATE_ALL_FAILURE';

export const SHOW_OR_HIDE_Q = 'SHOW_OR_HIDE_Q';

export const NEW_MESSAGE_IN_ADD_Q_TEXTAREA = 'NEW_MESSAGE_IN_ADD_Q_TEXTAREA';
export const NEW_CHECK_ATTR_IN_ADD_Q_CHECKBOX = 'NEW_CHECK_ATTR_IN_ADD_Q_CHECKBOX';
export const ADDING_Q_SUCCESS = 'ADDING_Q_SUCCESS';
export const ADDING_Q_FAILURE = 'ADDING_Q_FAILURE';

export const NEW_EDIT_Q_IS_SHOWN = 'NEW_EDIT_Q_IS_SHOWN';
export const NEW_MESSAGE_IN_EDIT_Q_TEXTAREA ='NEW_MESSAGE_IN_EDIT_Q_TEXTAREA';
export const NEW_CHECK_ATTR_IN_EDIT_Q_CHECKBOX = 'NEW_CHECK_ATTR_IN_EDIT_Q_CHECKBOX';
export const EDITING_Q_SUCCESS = 'EDITING_Q_SUCCESS';
export const EDITING_Q_FAILURE = 'EDITING_Q_FAILURE';

export const REMOVING_Q_SUCCESS = 'REMOVING_Q_SUCCESS';
export const REMOVING_Q_FAILURE = 'REMOVING_Q_FAILURE';

export const SHOW_OR_HIDE_A = 'SHOW_OR_HIDE_A';

export const NEW_MESSAGE_IN_ADD_A_TEXTAREA = 'NEW_MESSAGE_IN_ADD_A_TEXTAREA';
export const ADDING_A_SUCCESS = 'ADDING_A_SUCCESS';
export const ADDING_A_FAILURE = 'ADDING_A_FAILURE';

export const NEW_EDIT_A_IS_SHOWN = 'NEW_EDIT_A_IS_SHOWN';
export const NEW_MESSAGE_IN_EDIT_A_TEXTAREA = 'NEW_MESSAGE_IN_EDIT_A_TEXTAREA';
export const EDITING_A_SUCCESS = 'EDITING_A_SUCCESS';
export const EDITING_A_FAILURE = 'EDITING_A_FAILURE';

export const REMOVING_A_SUCCESS = 'REMOVING_A_SUCCESS';
export const REMOVING_A_FAILURE = 'REMOVING_A_FAILURE';
