export const PROJECT_VIEW_START_LOADING = 'PROJECT_VIEW_START_LOADING';
export const PROJECT_VIEW_END_LOADING = 'PROJECT_VIEW_END_LOADING';
export const PROJECT_VIEW_ERROR_LOADING = 'PROJECT_VIEW_ERROR_LOADING';
