export const REVIEW_SET_SELECTED_PROJECT = 'REVIEW_SET_SELECTED_PROJECT';
export const REVIEW_GET_ALL_PROJECTS_LOADING = 'REVIEW_GET_ALL_PROJECTS_LOADING';
export const REVIEW_GET_ALL_PROJECTS_SUCCESS = 'REVIEW_GET_ALL_PROJECTS_SUCCESS';
export const REVIEW_GET_ALL_PROJECTS_ERROR = 'REVIEW_GET_ALL_PROJECTS_ERROR';
export const REVIEW_GET_PROJECT_LOADING = 'REVIEW_GET_PROJECT_LOADING';
export const REVIEW_GET_PROJECT_SUCCESS = 'REVIEW_GET_PROJECT_SUCCESS';