export const SET_AUTH_USER_START_LOADING = 'SET_AUTH_USER_START_LOADING';
export const SET_AUTH_USER_END_LOADING = 'SET_AUTH_USER_END_LOADING';
export const SET_AUTH_USER_ERROR_LOADING = 'SET_AUTH_USER_ERROR_LOADING';