export const USERS_PROJECT_START_LOADING = 'USERS_PROJECT_START_LOADING';
export const USERS_PROJECT_END_LOADING = 'USERS_PROJECT_END_LOADING';
export const USERS_PROJECT_ERROR_LOADING = 'USERS_PROJECT_ERROR_LOADING';

export const PROJECTS_LIST_START_LOADING = 'PROJECTS_LIST_START_LOADING';
export const PROJECTS_LIST_END_LOADING = 'PROJECTS_LIST_END_LOADING';
export const PROJECTS_LIST_ERROR_LOADING = 'PROJECTS_LIST_ERROR_LOADING';

export const SAVE_PROJECT_USERS = 'SAVE_PROJECT_USERS';
export const SAVE_PROJECT_USERS_ERROR = 'SAVE_PROJECT_USERS_ERROR';

export const UPDATE_USER_RIGHT = 'UPDATE_USER_RIGHT';

