export const UP_CHANGE_OWNERSHIP_ED = 'UP_CHANGE_OWNERSHIP_ED';

export const UP_ADD_USER_TO_PROJECT_ED = 'UP_ADD_USER_TO_PROJECT_ED';
export const UP_REMOVE_USER_FROM_PROJECT_ED = 'UP_REMOVE_USER_FROM_PROJECT_ED';

export const UP_ADD_TAG_TO_PROJECT_ED = 'UP_ADD_TAG_TO_PROJECT_ED';
export const UP_ADD_NEW_TAG_TO_PROJECT_ED = 'UP_ADD_NEW_TAG_TO_PROJECT_ED';
export const UP_REMOVE_TAG_FROM_PROJECT_ED = 'UP_REMOVE_TAG_FROM_PROJECT_ED';
export const UP_REMOVE_NEW_TAG_FROM_PROJECT_ED = 'UP_REMOVE_NEW_TAG_FROM_PROJECT_ED';


export const UP_ADD_TECH_TO_PROJECT_ED = 'UP_ADD_TECH_TO_PROJECT_ED';
export const UP_ADD_NEW_TECH_TO_PROJECT_ED = 'UP_ADD_NEW_TECH_TO_PROJECT_ED';
export const UP_REMOVE_TECH_FROM_PROJECT_ED = 'UP_REMOVE_TECH_FROM_PROJECT_ED';
export const UP_REMOVE_NEW_TECH_FROM_PROJECT_ED = 'UP_REMOVE_NEW_TECH_FROM_PROJECT_ED';



export const UP_GET_DATA_ED = 'UP_GET_DATA_ED';
export const UP_GET_DATA_ERROR_ED = 'UP_GET_DATA_ERROR_ED';
export const UP_GET_DATA_SUCCESS_ED = 'UP_GET_DATA_SUCCESS_ED';


export const UP_POST_TAG_ED = 'UP_POST_TAG_ED';
export const UP_POST_TAG_ERROR_ED = 'UP_POST_TAG_ERROR_ED';
export const UP_POST_TAG_SUCCESS_ED = 'UP_POST_TAG_SUCCESS_ED';

export const UP_POST_TECH_ED = 'UP_POST_TECH_ED';
export const UP_POST_TECH_ERROR_ED = 'UP_POST_TECH_ERROR_ED';
export const UP_POST_TECH_SUCCESS_ED = 'UP_POST_TECH_SUCCESS_ED';


export const UP_POST_SECTION_ED = 'UP_POST_SECTION_ED';
export const UP_POST_SECTION_ERROR_ED = 'UP_POST_SECTION_ERROR_ED';
export const UP_POST_SECTION_SUCCESS_ED = 'UP_POST_SECTION_SUCCESS_ED';
export const UP_SELECT_SECTION_ED = 'UP_SELECT_SECTION_ED';


export const UP_POST_FEATURE_ED = 'UP_POST_FEATURE_ED';
export const UP_POST_FEATURE_ERROR_ED = 'UP_POST_FEATURE_ERROR_ED';
export const UP_POST_FEATURE_SUCCESS_ED = 'UP_POST_FEATURE_SUCCESS_ED';


export const UP_CHANGE_PROJECT_NAME_ED = 'UP_CHANGE_PROJECT_NAME_ED';
export const UP_CHANGE_PROJECT_LINK_ED = 'UP_CHANGE_PROJECT_LINK_ED';
export const UP_CHANGE_START_DATE_ED = 'UP_CHANGE_START_DATE_ED';
export const UP_CHANGE_FINISH_DATE_ED = 'UP_CHANGE_FINISH_DATE_ED';
export const UP_CHANGE_CONDITION_ED = 'UP_CHANGE_CONDITION_ED';
export const UP_CHANGE_DESCRIPTION_ED = 'UP_CHANGE_DESCRIPTION_ED';


export const UP_UPLOAD_FILE_ED = 'UP_UPLOAD_FILE_ED';
export const UP_UPLOAD_FILE_ERROR_ED = 'UP_UPLOAD_FILE_ERROR_ED';
export const UP_UPLOAD_FILE_SUCCESS_ED = 'UP_UPLOAD_FILE_SUCCESS_ED';

export const UP_UPLOAD_ICON_ED = 'UP_UPLOAD_ICON_ED';
export const UP_UPLOAD_ICON_ERROR_ED = 'UP_UPLOAD_ICON_ERROR_ED';
export const UP_UPLOAD_ICON_SUCCESS_ED = 'UP_UPLOAD_ICON_SUCCESS_ED';


export const UP_REMOVE_FILE_ED = 'UP_REMOVE_FILE_ED';



export const UP_CREATE_PROJECT_DATA_ED = 'UP_CREATE_PROJECT_DATA_ED';
export const UP_POST_PROJECT_ED = 'UP_POST_PROJECT_ED';
export const UP_POST_PROJECT_ERROR_ED = 'UP_POST_PROJECT_ERROR_ED';
export const UP_POST_PROJECT_SUCCESS_ED = 'UP_POST_PROJECT_SUCCESS_ED';



export const UP_POST_SECTION_DELETE_ED = 'UP_POST_SECTION_DELETE_ED';
export const UP_POST_FEATURE_DELETE_ED = 'UP_POST_FEATURE_DELETE_ED';
export const UP_CHANGE_STATUS_ED = 'UP_CHANGE_STATUS_ED';
export const UP_SET_CONTACT_FIELD_ED = 'UP_SET_CONTACT_FIELD_ED';
export const UP_SELECT_USER_ED = 'UP_SELECT_USER_ED';
export const UP_SET_USER_START_DATE_ED = 'UP_SET_USER_START_DATE_ED';
export const UP_SET_USER_END_DATE_ED = 'UP_SET_USER_END_DATE_ED';

export const SET_VISIBLE_FORM_BY_LINK_ATTACHMENTS_ED = 'SET_VISIBLE_FORM_BY_LINK_ATTACHMENTS';
export const SET_VISIBLE_FORM_BY_LINK_SCREENSHOOTS_ED = 'SET_VISIBLE_FORM_BY_LINK_SCREENSHOOTS';
export const SET_VISIBLE_ADD_TECH_FORM_ED = 'SET_VISIBLE_ADD_TECH_FORM';

export const UP_SET_LOCATION_ED = 'UP_SET_LOCATION';

