export const CHANGE_OWNERSHIP = 'CHANGE_OWNERSHIP';
export const ADD_USER_TO_PROJECT = 'ADD_USER_TO_PROJECT';
export const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT';


export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_PROJECT_LINK = 'CHANGE_PROJECT_LINK';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_FINISH_DATE = 'CHANGE_FINISH_DATE';
export const CHANGE_CONDITION = 'CHANGE_CONDITION';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';

	        	
	        