export const CHANGE_OWNERSHIP = 'CHANGE_OWNERSHIP';

export const ADD_USER_TO_PROJECT = 'ADD_USER_TO_PROJECT';
export const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT';

export const ADD_TAG_TO_PROJECT = 'ADD_TAG_TO_PROJECT';
export const ADD_NEW_TAG_TO_PROJECT = 'ADD_NEW_TAG_TO_PROJECT';
export const REMOVE_TAG_FROM_PROJECT = 'REMOVE_TAG_FROM_PROJECT';
export const REMOVE_NEW_TAG_FROM_PROJECT = 'REMOVE_NEW_TAG_FROM_PROJECT';


export const ADD_TECH_TO_PROJECT = 'ADD_TECH_TO_PROJECT';
export const ADD_NEW_TECH_TO_PROJECT = 'ADD_NEW_TECH_TO_PROJECT';
export const REMOVE_TECH_FROM_PROJECT = 'REMOVE_TECH_FROM_PROJECT';
export const REMOVE_NEW_TECH_FROM_PROJECT = 'REMOVE_NEW_TECH_FROM_PROJECT';



export const GET_DATA = 'GET_DATA';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';


export const CHECK_IF_TAG_EXIST = 'CHECK_IF_TAG_EXIST';
export const POST_TAG = 'POST_TAG';
export const POST_TAG_ERROR = 'POST_TAG_ERROR';
export const POST_TAG_SUCCESS = 'POST_TAG_SUCCESS';




export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_PROJECT_LINK = 'CHANGE_PROJECT_LINK';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_FINISH_DATE = 'CHANGE_FINISH_DATE';
export const CHANGE_CONDITION = 'CHANGE_CONDITION';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';

	        	
	        